#!/bin/bash

#
# Do not edit this file!
# This file is generated by a generator contain in make directory.
# This file and the generator is published under Creative Commons Zero 1.0 License or later
# http://creativecommons.org/publicdomain/zero/1.0/deed
#


function final {
:

}

trap final EXIT

mkdir -p "./build"
mv "./build/dts/LICENSE.txt" "./src/LICENSE-rtm-mc-wrapper.txt"
cd "./src"
zip -r "../build/out.zip" ./*
rm -rf "./LICENSE-rtm-mc-wrapper.txt"


