#
# Do not edit this file!
# This file is generated by a generator contain in make directory.
# This file and the generator is published under Creative Commons Zero 1.0 License or later
# http://creativecommons.org/publicdomain/zero/1.0/deed
#


function final {

}

try {
$null = New-Item -ItemType Directory -ea 0 -Path "./build"
Move-Item "./build/dts/LICENSE.txt" "./src/LICENSE-rtm-mc-wrapper.txt"
Set-Location "./src"
Compress-Archive -Path ./* -DestinationPath  "../build/out.zip"
$null = Remove-Item -Recurse -Force -ea 0 -Path "./LICENSE-rtm-mc-wrapper.txt"

} finally {
final
}

