#
# Do not edit this file!
# This file is generated by a generator contain in make directory.
# This file and the generator is published under Creative Commons Zero 1.0 License or later
# http://creativecommons.org/publicdomain/zero/1.0/deed
#
$tmpFile=New-TemporaryFile
$tempDir=New-TemporaryFile


function final {
$null = Remove-Item -Recurse -Force -ea 0 -Path $tmpFile
$null = Remove-Item -Recurse -Force -ea 0 -Path $tempDir

}

try {
$null = Remove-Item -Recurse -Force -ea 0 -Path $tempDir
$null = New-Item -ItemType Directory -ea 0 -Path $tempDir
$dtsDir="./build/dts"
$config = get-content "./config.txt" | ConvertFrom-StringData
$config_version = $config.config_version
$config_included = $config.config_included
function move-dts ($1) {
$null = Remove-Item -Recurse -Force -ea 0 -Path "$dtsDir/${1}"
Move-Item "$tempDir/${1}" "$dtsDir/${1}"
}
$zipUrl="https://github.com/anatawa12/rtm-mc-wrapper/releases/download/${config_version}/rtm-mc-wrapper-${config_version}.zip"
$null = Remove-Item -Recurse -Force -ea 0 -Path $dtsDir
$null = New-Item -ItemType Directory -ea 0 -Path $dtsDir
Invoke-WebRequest -Uri $zipUrl -OutFile $tmpFile
Expand-Archive -Path $tmpFile -DestinationPath $tempDir
move-dts "api.d.ts"
move-dts "rhino-import.d.ts"
move-dts "LICENSE.txt"
if ([System.IO.File]::Exists("$tempDir/api.included.${config_included}.d.ts")) {
move-dts "api.included.${config_included}.d.ts"
} else {
Write-Output "warn: invalid included version name. the version not found: ${config_included}"
}

} finally {
final
}

