#!/bin/bash

#
# Do not edit this file!
# This file is generated by a generator contain in make directory.
# This file and the generator is published under Creative Commons Zero 1.0 License or later
# http://creativecommons.org/publicdomain/zero/1.0/deed
#
tmpFile="$(mktemp)"
tempDir="$(mktemp)"


function final {
:
rm -rf "$tmpFile"
rm -rf "$tempDir"

}

trap final EXIT

rm -rf "$tempDir"
mkdir -p "$tempDir"
dtsDir="./build/dts"
. "./config.txt"
function move-dts {
rm -rf "$dtsDir/${1}"
mv "$tempDir/${1}" "$dtsDir/${1}"
}
zipUrl="https://github.com/anatawa12/rtm-mc-wrapper/releases/download/${config_version}/rtm-mc-wrapper-${config_version}.zip"
rm -rf "$dtsDir"
mkdir -p "$dtsDir"
wget -q "$zipUrl" -O "$tmpFile"
unzip -qq "$tmpFile" -d "$tempDir"
move-dts "api.d.ts"
move-dts "rhino-import.d.ts"
move-dts "LICENSE.txt"
if [ -f "$tempDir/api.included.${config_included}.d.ts" ]; then
move-dts "api.included.${config_included}.d.ts"
else
echo "warn: invalid included version name. the version not found: ${config_included}"
fi


